name: Error
description: Something doesnt work
body:
  - type: textarea
    id: repro
    attributes:
      label: Observed Behavior
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true


